### ISSUE TITLE
default dependency is missing - obviously mandatory for IP16

### ISSUE THREAD

**Issue by geetee13** [duncanford/pw-code-generator#2]
Under some strange conditions it is necessary with IP16 to have the basePW defined. 
(This was not necessary with IP15, the dependecy list has to be empty with IP15!)

The generator should generate the define-line with [siebel/basePW] as dependency.

Take into account the differences between IP15 and IP16.

(I mean the following with strange conditions: IE, IP16, login with singe-sign-on. If these are fulfilled, openui does not start, but brings an error to the console. Chrome works...)

**Comment by duncanford** [comment]
I'm not sure why this would be important. I'd have to go through and check to be certain, but I believe all of the PWs that are extended through this generator are themselves already defined with basePW as their dependency, which means all code from this generator has an implicit dependency on basePW implicitly. I'll check this and report back.

**Comment by duncanford** [comment]
Quick investigation makes me think that, as there's no file siebel/basePW.js, the dependency in IP16 should actually be against siebel/pwinfra, not siebel/basepw. I'll continue this investigation and potentially have to create a dropdown to select IP15 or IP16 in order to generate the right template for each release.

**Comment by geetee13** [comment]
That was also my thought, but only this works. I tried this , because I saw
it exactly so in a SR on supportWeb.



Am 24.01.2017 17:25 schrieb "Duncan Ford" <notifications@github.com>:

Quick investigation makes me thing that, as there's no file
siebel/basePW.js, the dependency in IP16 should actually be against
siebel/pwinfra, not siebel/basepw. I'll continue this investigation and
potentially have to create a dropdown to select IP15 or IP16 in order to
generate the right template for each release.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/duncanford/pw-code-generator/issues/2#issuecomment-274854357>,
or mute the thread

**Comment by duncanford** [comment]
Could you specify the SR please?

**Comment by geetee13** [comment]
You have to wait for tomorrow. .. I don't find it on the mobile page...

Am 24.01.2017 18:39 schrieb "Duncan Ford" <notifications@github.com>:

**Comment by geetee13** [comment]
I've found a solution with my colleague, so the SR ist not for relevance any more. Just for completeness, here is the SR:
https://support.oracle.com/epmos/faces/DocumentDisplay?id=2060294.1&displayIndex=1
IP15: Custom Plug-in Wrapper JS File Not Picked In Application And No Effect On Expected Controls (Doc ID 2060294.1)

**Comment by geetee13** [comment]
What is missing is the "siebel/FieldPW" as dependency. This can be found also in pwinfra, just like the basepw. Please forget my initial comment, stating that "basePW is required as dependency". I must have made an error while testing.

Because of the generated extend:
SiebelJS.Extend(myPW, SiebelAppFacade.FieldPW);
is "FieldPW" required. This will be loaded too late under some circumstances without defining a dependency.
And this works also in IP15 and in IP16, so we don't need a further combobox :-)

Strange is, that the error comes only on IE running in Citrix... IE on a local machine works...

**Comment by duncanford** [comment]
And was there a particular set of option you were using that didn't auto-generate the dependency on FieldPW?

**Comment by geetee13** [comment]
oh, OK, i was a bit misunderstandable about what we mean. The line with extend...fieldPW was generated correctly also earlier.
What we mean is: the generated line ("...Extend...")
SiebelJS.Extend(myPW, SiebelAppFacade.FieldPW);
is correct.
The other generated line 
define("siebel/custom/myPW", [],
does not match the ...Extend... line : there should be the dependency ["siebel/FieldPW"] specified, in order to force loading the FieldPW at the first instantiation of myPW before the initialization actually uses FieldPW for extending.

**Comment by duncanford** [comment]
I get it now. In fact, the define statement is completely missing the dependency in all cases. Well spotted. Will fix this. Thanks.

**Comment by duncanford** [comment]
It's still not clear why your situation generates an error. pwinfra.js is forced by manifest to load very early in the manifest evaluation sequence. It still feels right that we declare a dependency here, but it will take longer to declare all dependencies specifically for each selected control type. Therefore I've initially set all new pw code to use siebel/basepw as the dependency, which is the first thing defined in pwinfra. Once pwinfra is loaded, basepw will be defined, along with all other plugin wrappers that this generator can extend. Could you test the new generator in your situation that fails and let me know if this fixes the issue please?

**Comment by geetee13** [comment]
i tried with only the basepw and it does not work. But, there is a difference in the console, which gives us some hint, why.
I have 1 or more line in the console BEFORE the actual error from myPW will be logged, when the PW does not work. It is a bit misterious: "superClass is undefined @ SiebJS.Extend ". This is important, as the broken myPW throws an error stating that myPW.superclass is null or undefined.

with empty dependency, i get 2x the misterious line. (one from myPW, missing fieldPW and one from fieldPW, missing basepw)
with dependency including only the basepw, i get only one misterious line. (from myPW, missing fieldPW)
with dependency including only FieldPW has no such lines and myPW works.

I think, one part is to load a js-file with one or more modules (basepw, fieldpw) in it. The second part is, at what time will be the modules of this js-file effectively "loaded" by the AMD-Framework. I think, it has a ruleset how to load them, just like any other package manager has. But, i'm sure, they will not have a rule "load the js-file and load the modules in it instantly'.
In my case, i think, i define the fieldPW, and somehow, basepw is already loaded also as module. But, i have only luck with the timing.
Just to go for sure, FieldPW (in pwinfra) has to define it own dependency to basepw (as it extends only basepw). 
On the other side, myPW - which extends only fieldPW should define only fieldpw as a dependency. 
And, you are right, if i use another PW, such as ButtonPW, i have to define a dependecy according to it, and also an extend... must match buttonPW.
So i think, pwinfra has also a bug...

**Comment by duncanford** [comment]
Could you try "siebel/pwinfra" as the dependency please? I think fieldpw won't really help as there is no file of that name.

**Comment by stefanciprian** [comment]
Please confirm that these problems happen only when using Citrix. Probably there is something wrong with the environment and is causing some sorts of delays.

From what I remember, hope that I am not wrong here, you can check if the dependencies are loaded or not using:

```
SiebelJS.Log(require.defined("some/dependency"));
//returns true or false
```

**Comment by geetee13** [comment]
@stefan:
i observed this behaviour reproducible only on Citrix. However, we had the issue sporadic also on a local Client.
But, there is nothing wrong with the Environments: it is the nature of the web and also of the execution of the particular JavaScript code. Latter even more important, because openui uses the "define"-s which can cause also additional asynchronism - i.e. stop the execution of the current function and wait for another one before executing the current one...
The delays should be handled in a safe way. See my next post also.

**Comment by geetee13** [comment]
@duncanford 
first regarding my previous Statement "pwinfra has a bug": yes IP15 has, but this was fixed in IP16. Where to check?: if you look at the dependency-definition for example in the module 'siebel/FieldPW' in pwinfra.js, it has now with IP16 his dependency to "siebel/basepw".

regarding the discussion "FieldPW vs. pwinfra":
both of them are valid entries for "define(...)". "define" accepts filenames AND names of named modules also. Latter is "siebel/FieldPW", former is "siebel/pwinfra". 
I have tested: "siebel/pwinfra" works, just like "siebel/FieldPW".
The question is, which one is the right way for the Generator?
A particular myPW can implement/extend just one control-type: either FieldPW or ButtonPW or .... 
In case of using control-type specific dependencies, the possibility to load only the used module is there.
In case of using 'pwinfra', every control-type will be loaded, even if it is not used by the particular myPW. 
On the other Hand, the _actual_ implementation of OpenUI loads every type, regardless of usage. That's because of the same file. So actually, it does not matter, which way we use...

**Comment by duncanford** [comment]
If you find that siebel/pwinfra as a dependency works, then I believe this is a better default that basepw or FieldPW. The reason is that if a dependecy is declared on basepw, an attempt will be made to load siebel/basepw.js if pwinfra is not already loaded, which doesn't exist. This would then lead to multiple failure conditions. Meanwhile, a dependency on pwinfra will cause pwinfra.js to load, if it hasn't already. The dependency on pwinfra should not be considered satisfied until the file has been processed, which will in turn will define all other PWs that can be extended. However, I think the problem seems to be limited to a very small subset of deployments; i.e. Citrix-based. I'll set the dependency to pwinfra and close this issue.

Many thanks for bringing this issue to light!
