### ISSUE TITLE
RadioPW

### ISSUE THREAD

**Issue by gkali** [duncanford/pw-code-generator#3]
Hi Duncan!

I have noticed a Bug in your Plugin Wrapper generator. I was trying to use it to create a PW for a Radio Button Control. Unfortunately, I got an Error when I tried to run the generated code. 
The Parent class, from which the custom PW should have extended, was wrong. It gave me SiebelAppFacade.PhysicalRenderer, but it should be SiebelAppFacade.RadioPW.

--SiebelJS.Extend(SliderPW, SiebelAppFacade.PhysicalRenderer);

**Comment by duncanford** [comment]
Thanks for reporting this issue.
